gardenr/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tools, except: [:destroy]
  resources :users, except: [:index]
  get '/', to: 'tools#index', as: 'home'
end

gardenr/app/models/tool.rb
class Tool < ApplicationRecord
  validates :name, presence: true
  validates :condition, presence: true
  belongs_to :user
end

gardenr/app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  has_many :tools
end

gardenr/app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :find_tool, only: [:show, :edit, :update]

  def index
    @tools = Tool.all
  end

  def show
    # find_tool
  end

  def new
    @users = User.all
    @tool = Tool.new
  end

  def create
    @tool = Tool.new(tool_params)

    if @tool.save
      redirect_to tools_path
    else
      @errors = @tool.errors.full_messages
      render :new
    end
  end

  def edit
    @users = User.all
    # find_tool
  end

  def update
    # @tool has been set by our before action
    @tool.assign_attributes(tool_params)

    if @tool.save
      redirect_to tool_path(@tool)
    else
      @errors = @tool.errors.full_messages
      render :edit
    end
  end

  private

  def find_tool
    @tool = Tool.find_by(id: params[:id])
  end

  def tool_params
    params.require(:tool).permit(:name, :condition, :user_id)
  end
end

gardenr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gardenr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

gardenr/app/views/tools/edit.html.erb
<h1>Edit This Tool</h1>

<% if @errors %>
  <% @errors.each do |error| %>
    <p><%= error %></p>
  <% end %>
<% end %>
<%= form_for @tool do |f| %>
  <%= f.label :name %>
  <p><%= f.text_field :name %></p>
  <%= f.label :condition %>
  <p><%= f.text_field :condition %></p>
  <%= f.collection_select :user_id, @users, :id, :name %>
  <%= f.submit "I DO think so Tim" %>
<% end %>

gardenr/app/views/tools/index.html.erb
<h1>All Tools</h1>

<%= link_to "Create New Tool", new_tool_path %>
<% @tools.each do |tool| %>
  <p><%= link_to(tool.name, tool_path(tool)) %></p>
<% end %>

gardenr/app/views/tools/new.html.erb
<h1>Create New Tool</h1>
<% if @errors %>
  <% @errors.each do |error| %>
    <p><%= error %></p>
  <% end %>
<% end %>

<%= form_for @tool do |f| %>
  <%= f.label :name %>
  <p><%= f.text_field :name %></p>
  <%= f.label :condition %>
  <p><%= f.text_field :condition %></p>
  <%= f.collection_select :user_id, @users, :id, :name %>
  <%= f.submit "I DO think so Tim" %>
<% end %>

gardenr/app/views/tools/show.html.erb
<h1>Tool Details</h1>

<p>Name: <%= @tool.name %></p>
<p>Condition: <%= @tool.condition %></p>
<%= link_to "Edit Tool", edit_tool_path(@tool) %>
<%= link_to "Back to Tools", tools_path %>