19 - Rails Forms and REST/config/routes.rb
Rails.application.routes.draw do
  resources :textbooks
  resources :cohorts do
    resources :students, except: [:destroy]
  end
  # get "/students", to: "students#index", as: :students
  resources :students, except: [:destroy]

  # NAMING CUSTOM ROUTES
  # get "/", to: "cohorts#welcome", as: :welcome
  # get "/login", to: "sessions#new", as: :login

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

19 - Rails Forms and REST/app/models/cohort.rb
class Cohort < ApplicationRecord
  has_many :students
  validates :name, presence: true, uniqueness: true
  validates :name, format: { with: /\A[a-zA-Z0-9-]+\z/,
    message: "must contain only letters, numbers, and dashes" }
end

19 - Rails Forms and REST/app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :student
  belongs_to :textbook
end

19 - Rails Forms and REST/app/models/student.rb
class Student < ApplicationRecord
  has_many :rentals
  has_many :textbooks, through: :rentals
  belongs_to :cohort

  accepts_nested_attributes_for :textbooks, reject_if: proc { |attributes| p attributes; attributes['title'].include?("hate") }
end

19 - Rails Forms and REST/app/models/textbook.rb
class Textbook < ApplicationRecord
  has_many :rentals
  has_many :students, through: :rentals

  validates :vandalized, inclusion: { in: [true, false],
    message: "%{value} is not valid, please select true or false" }
  validate :title_starts_with_word_the

  def title_starts_with_word_the
    if title.downcase[0..3] != "the "
      errors.add(:title, "must begin with the word 'the' followed by at least one space")
    end
  end
end

19 - Rails Forms and REST/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

19 - Rails Forms and REST/app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  def index
    @cohorts = Cohort.all
  end

  def show
    @cohort = Cohort.find(params[:id])
  end

  def new
    @cohort = Cohort.new
  end

  def create
    @cohort = Cohort.new(cohort_params)

    if @cohort.save
      redirect_to '/cohorts'
    else
      @errors = @cohort.errors.full_messages
      render :new
    end
  end

  def edit
    @cohort = Cohort.find(params[:id])
  end

  def update
    @cohort = Cohort.find(params[:id])

    if @cohort.update(cohort_params)
      redirect_to "/cohorts/#{@cohort.id}"
    else
      render :edit
    end
  end

  def delete
    Cohort.destroy(params[:id])
  end

  private

  def cohort_params
    params.require(:cohort).permit(:name)
  end
end

19 - Rails Forms and REST/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    if params[:cohort_id]
      @cohort = Cohort.find(params[:cohort_id])
      @students = @cohort.students
    else
      @students = Student.all
    end
  end

  def new
    @cohorts = Cohort.all
    @cohort = Cohort.find_by(id: params[:cohort_id])
    @student = Student.new
    @student.textbooks.build([{}, {}])
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_url
    else
      @errors = @student.errors.full_messages

      @cohorts = Cohort.all
      render :new
    end
  end

  private

  def student_params
    params.require(:student).permit(:name, :cohort_id, textbooks_attributes: [:vandalized, :title])
  end
end

19 - Rails Forms and REST/app/controllers/textbooks_controller.rb
class TextbooksController < ApplicationController
  
end

19 - Rails Forms and REST/app/helpers/cohorts_helper.rb
module CohortsHelper
end

19 - Rails Forms and REST/app/helpers/district_helper.rb
module DistrictHelper
end

19 - Rails Forms and REST/app/helpers/students_helper.rb
module StudentsHelper
end

19 - Rails Forms and REST/app/helpers/textbooks_helper.rb
module TextbooksHelper
end

19 - Rails Forms and REST/app/views/cohorts/edit.html.erb
<%= @cohort.name %>
<form action="/cohorts/<%= @cohort.id %>" method="post">
  <input name="_method" type="hidden" value="patch" />
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>
    <input type="text" name="cohort[name]" value="<%= @cohort.name %>">
  </label>

  <input type="submit">
</form>

19 - Rails Forms and REST/app/views/cohorts/index.html.erb
<h1>Cohorts</h1>
<nav>
  <ul>
    <li>
      <%= link_to("Create new cohort", new_cohort_path) %>
    </li>
  </ul>
</nav>
<ul>
  <% @cohorts.each do |cohort| %>
    <li>
      <a href="/cohorts/<%= cohort.id %>"><%= cohort.name %></a>
    </li>
  <% end %>
</ul>

19 - Rails Forms and REST/app/views/cohorts/new.html.erb
<% if @errors %>
  <% @errors.each do |error_msg| %>
    <p><%= error_msg %></p>
  <% end %>
<% end %>

<%= form_for(@cohort) do |cohort_form| %>
  <%= cohort_form.label :name, "Cohort Name" %>
  <%= cohort_form.text_field :name %>
  <%= cohort_form.submit "Make One!" %>
<% end %>

19 - Rails Forms and REST/app/views/cohorts/show.html.erb
<h1><%= @cohort.name %></h1>
<a href="/cohorts/<%= @cohort.id %>/edit">Edit</a>

19 - Rails Forms and REST/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFormsRest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

19 - Rails Forms and REST/app/views/students/index.html.erb
<h1>Students</h1>

<%= link_to("Create New Student", new_student_path) %>

<% @students.each do |student| %>
  <p><%= student.name %></p>
  <p><%= student.cohort.name %></p>
  <hr>
<% end %>

19 - Rails Forms and REST/app/views/students/new.html.erb
<% if @errors %>
  <% @errors.each do |error_msg| %>
    <p><%= error_msg %></p>
  <% end %>
<% end %>

<%= form_for(@student) do |f| %>
  Name: <%= f.text_field :name %>
  Cohort: <%= f.collection_select :cohort_id, @cohorts, :id, :name, { :selected => @cohort.try(:id) } %>
  <br>
  <%= f.fields_for :textbooks do |textbooks_form| %>
    Textbook title: <%= textbooks_form.text_field :title %>
    <br>
    Vandalized? (True/false): <%= textbooks_form.text_field :vandalized %>
    <br>
  <% end %>

  <%= f.submit %>
<% end %>